export const WORD_CATEGORIES = ["全部", "自然", "时间", "地点", "心情"];

export const WORD_LIBRARY = [
  { word: "雨", category: "自然" },
  { word: "苔藓", category: "自然" },
  { word: "风", category: "自然" },
  { word: "树影", category: "自然" },
  { word: "月光", category: "自然" },
  { word: "霜冻", category: "自然" },
  { word: "十月", category: "时间" },
  { word: "黄昏", category: "时间" },
  { word: "清晨", category: "时间" },
  { word: "午夜", category: "时间" },
  { word: "星期二", category: "时间" },
  { word: "格拉斯哥", category: "地点" },
  { word: "站台", category: "地点" },
  { word: "咖啡馆", category: "地点" },
  { word: "窗边", category: "地点" },
  { word: "河岸", category: "地点" },
  { word: "想念", category: "心情" },
  { word: "犹豫", category: "心情" },
  { word: "温柔", category: "心情" },
  { word: "孤独", category: "心情" },
  { word: "安静", category: "心情" },
];
